export const GET_PRODUCT_RATING_REQUEST = 'GET_PRODUCT_RATING_REQUEST';
export const GET_PRODUCT_RATING_SUCCESS = 'GET_PRODUCT_RATING_SUCCESS';
export const GET_PRODUCT_RATING_FAILURE = 'GET_PRODUCT_RATING_FAILURE';

