export const GET_NAV_REQUEST = 'GET_NAV_REQUEST';
export const GET_NAV_SUCCESS = 'GET_NAV_SUCCESS';
export const GET_NAV_FAILURE = 'GET_NAV_FAILURE';

export const CREATE_CAT_REQUEST = 'CREATE_CAT_REQUEST';
export const CREATE_CAT_SUCCESS = 'CREATE_CAT_SUCCESS';
export const CREATE_CAT_FAILURE = 'CREATE_CAT_FAILURE';

export const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAILURE = 'GET_LIST_FAILURE';